title: "Telenor Makerspace Fornebu"
description: "Info about the makerspace we have at the Telenor headquarters in Fornebu, Norway"
baseurl: ""
url: "https://fornebumakerspace.github.io"
github_username: FornebuMakerspace

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-sitemap
